ENH Add userform docs
silverstripe/doc.silverstripe.org pull request #291
Opened 2024-04-08 05:59 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-userforms/issues/1266

2024-04-08 21:53 UTC, GuySartorelli requested changes

2024-04-08 21:53 UTC, GuySartorelli commented on sources-user.js
> +  },
```suggestion
```
Userforms is already in user help.

2024-04-08 22:48 UTC, emteknetnz commented on sources-user.js
> +  },
Removed

2024-04-09 03:13 UTC, GuySartorelli approved these changes
LGTM, will merge when docs are merged

2024-04-09 04:38 UTC, merged